import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import { HeaderSection } from "./page";

const vazir = Vazirmatn({ subset: ["arabic"]});


export const metadata: Metadata = {
  title: "Pishraft",
  description: "Generated by TodoApp",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa-Ir" suppressHydrationWarning>
      <body
        className={vazir.className}
      >
        <HeaderSection />
        {children}
      </body>
    </html>
  );
}
