import type { Metadata } from "next";
import { Estedad } from "next/font/google";
import "./globals.css";

const amiri = Estedad({ subset: ["arabic"]});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa-Ir" suppressHydrationWarning>
      <body
        className={amiri.className}
      >
        {children}
      </body>
    </html>
  );
}
